"""finance: управленческий учёт компании

Схема раздела «Финансы»: счета, справочники, операции, планы и партии импорта.
Раздел заведён как обкатка перед интеграцией с внешним сервисом учёта, поэтому
устройство схемы выбрано так, чтобы её было дешево выкинуть целиком:
`DROP SCHEMA finance CASCADE` не задевает ни одну чужую таблицу.

Что заложено сразу и почему
───────────────────────────
**Сумма неотрицательная, направление задаёт `kind`** (CHECK `amount >= 0`).
Знак и вид операции одновременно — два источника правды об одном: строка
«доход на минус пять тысяч» смысла не имеет, но записалась бы. Знак живёт
только на входе, в разборе файла и формы.

**Две даты платежа и начисления** (`paid_at`, `accrued_at`) с индексом на
каждую. Отчёт о движении денег считается по первой, прибыль — по второй; одна
дата сделала бы невозможным главный вопрос управленческого учёта.

**Отпечаток строки источника** (`uq_operations_external_key`). По нему повторная
загрузка того же файла не заводит вторые копии. Уникальность частичная по
смыслу: у операций, набранных руками, отпечатка нет, и NULL в Postgres не
конфликтуют между собой.

**Партии импорта живут после применения** (`import_batches`, `import_rows`).
Это не журнал ради журнала: отложенная строка правится и заводится по одной,
без перезагрузки файла. Ради этого свойства раздел и написан — импортёры,
которые мы проверяли, отменяли весь файл из-за одной строки.

**Деньги — `numeric(18,2)`, курс — `numeric(18,6)`.** Сумма тысячи строк по
копейкам на двоичной плавающей точке не сходится, а курс, округлённый до
копеек, даёт расхождение на крупной сумме.

**Текст с `CHECK` вместо `ENUM`** и единая схема имён ограничений из
`finance/db.py` — по тем же причинам, что в ревизии 0010.

Revision ID: 0012
Revises: 0011
Create Date: 2026-09-17 23:32:07.869920

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0012'
down_revision: Union[str, None] = '0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SCHEMA = "finance"


def upgrade() -> None:
    bind = op.get_bind()
    # У SQLite схем нет — там модуль собирается через create_all из тех же
    # моделей (app/finance/db.py), и ревизия ему не нужна.
    if bind.dialect.name == "sqlite":
        return

    # Автогенерация создание схемы не выдаёт: она видит только таблицы.
    op.execute(f'CREATE SCHEMA IF NOT EXISTS "{SCHEMA}"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('base_currency', sa.Text(), server_default=sa.text("'KZT'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces')),
    sa.UniqueConstraint('slug', name=op.f('uq_workspaces_slug')),
    schema='finance'
    )
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), server_default=sa.text("'bank'"), nullable=False),
    sa.Column('currency', sa.Text(), server_default=sa.text("'KZT'"), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('excluded_from_reports', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('bank', 'cash', 'card', 'safe', 'crypto', 'other')", name=op.f('ck_accounts_account_kind')),
    sa.ForeignKeyConstraint(['workspace_id'], ['finance.workspaces.id'], name=op.f('fk_accounts_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('workspace_id', 'normalized_name', name='uq_accounts_workspace_name'),
    schema='finance'
    )
    op.create_index(op.f('ix_accounts_workspace_id'), 'accounts', ['workspace_id'], unique=False, schema='finance')
    op.create_index('ix_accounts_workspace_id_position', 'accounts', ['workspace_id', 'position'], unique=False, schema='finance')
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('side', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('system_key', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("side IN ('income', 'expense')", name=op.f('ck_categories_category_side')),
    sa.ForeignKeyConstraint(['parent_id'], ['finance.categories.id'], name=op.f('fk_categories_parent_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['finance.workspaces.id'], name=op.f('fk_categories_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('workspace_id', 'side', 'parent_id', 'normalized_name', name='uq_categories_name'),
    schema='finance'
    )
    op.create_index(op.f('ix_categories_workspace_id'), 'categories', ['workspace_id'], unique=False, schema='finance')
    op.create_index('ix_categories_workspace_id_side', 'categories', ['workspace_id', 'side'], unique=False, schema='finance')
    op.create_table('counterparties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Text(), server_default=sa.text("'client'"), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('client', 'supplier', 'staff', 'owner', 'creditor', 'borrower', 'tax')", name=op.f('ck_counterparties_counterparty_role')),
    sa.ForeignKeyConstraint(['workspace_id'], ['finance.workspaces.id'], name=op.f('fk_counterparties_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_counterparties')),
    sa.UniqueConstraint('workspace_id', 'role', 'normalized_name', name='uq_counterparties_name'),
    schema='finance'
    )
    op.create_index(op.f('ix_counterparties_workspace_id'), 'counterparties', ['workspace_id'], unique=False, schema='finance')
    op.create_index('ix_counterparties_workspace_id_role', 'counterparties', ['workspace_id', 'role'], unique=False, schema='finance')
    op.create_table('import_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'preview'"), nullable=False),
    sa.Column('mapping', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('decisions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('rows_total', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rows_imported', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rows_failed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rows_duplicate', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('preview', 'applied', 'cancelled')", name=op.f('ck_import_batches_import_batch_status')),
    sa.ForeignKeyConstraint(['workspace_id'], ['finance.workspaces.id'], name=op.f('fk_import_batches_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches')),
    schema='finance'
    )
    op.create_index(op.f('ix_import_batches_workspace_id'), 'import_batches', ['workspace_id'], unique=False, schema='finance')
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('closed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['finance.projects.id'], name=op.f('fk_projects_parent_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['finance.workspaces.id'], name=op.f('fk_projects_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('workspace_id', 'parent_id', 'normalized_name', name='uq_projects_name'),
    schema='finance'
    )
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False, schema='finance')
    op.create_index('ix_projects_workspace_id_position', 'projects', ['workspace_id', 'position'], unique=False, schema='finance')
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['finance.workspaces.id'], name=op.f('fk_tags_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('workspace_id', 'normalized_name', name='uq_tags_name'),
    schema='finance'
    )
    op.create_index(op.f('ix_tags_workspace_id'), 'tags', ['workspace_id'], unique=False, schema='finance')
    op.create_table('operations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'fact'"), nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=False),
    sa.Column('accrued_at', sa.Date(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.Text(), server_default=sa.text("'KZT'"), nullable=False),
    sa.Column('amount_base', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), server_default=sa.text('1'), nullable=False),
    sa.Column('account_from_id', sa.Uuid(), nullable=True),
    sa.Column('account_to_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('counterparty_id', sa.Uuid(), nullable=True),
    sa.Column('comment', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('split_state', sa.Text(), server_default=sa.text("'none'"), nullable=False),
    sa.Column('source', sa.Text(), server_default=sa.text("'app'"), nullable=False),
    sa.Column('external_key', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.Uuid(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_by', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("kind IN ('income', 'expense', 'transfer')", name=op.f('ck_operations_operation_kind')),
    sa.CheckConstraint("source IN ('app', 'grid', 'import', 'api')", name=op.f('ck_operations_operation_source')),
    sa.CheckConstraint("split_state IN ('none', 'exact', 'partial', 'mismatch')", name=op.f('ck_operations_operation_split_state')),
    sa.CheckConstraint("status IN ('fact', 'plan')", name=op.f('ck_operations_operation_status')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_operations_operation_amount_sign')),
    sa.ForeignKeyConstraint(['account_from_id'], ['finance.accounts.id'], name=op.f('fk_operations_account_from_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['account_to_id'], ['finance.accounts.id'], name=op.f('fk_operations_account_to_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['finance.categories.id'], name=op.f('fk_operations_category_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['finance.counterparties.id'], name=op.f('fk_operations_counterparty_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['finance.import_batches.id'], name=op.f('fk_operations_import_batch_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['finance.workspaces.id'], name=op.f('fk_operations_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operations')),
    sa.UniqueConstraint('workspace_id', 'external_key', name='uq_operations_external_key'),
    schema='finance'
    )
    op.create_index(op.f('ix_operations_workspace_id'), 'operations', ['workspace_id'], unique=False, schema='finance')
    op.create_index('ix_operations_workspace_id_accrued_at', 'operations', ['workspace_id', 'accrued_at'], unique=False, schema='finance')
    op.create_index('ix_operations_workspace_id_paid_at', 'operations', ['workspace_id', 'paid_at'], unique=False, schema='finance')
    op.create_index('ix_operations_workspace_id_status', 'operations', ['workspace_id', 'status'], unique=False, schema='finance')
    op.create_table('plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('side', sa.Text(), nullable=False),
    sa.Column('method', sa.Text(), server_default=sa.text("'cash'"), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('comment', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_by', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('cash', 'accrual')", name=op.f('ck_plans_plan_method')),
    sa.CheckConstraint("side IN ('income', 'expense')", name=op.f('ck_plans_plan_side')),
    sa.ForeignKeyConstraint(['category_id'], ['finance.categories.id'], name=op.f('fk_plans_category_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['finance.projects.id'], name=op.f('fk_plans_project_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['finance.workspaces.id'], name=op.f('fk_plans_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('workspace_id', 'month', 'side', 'method', 'category_id', 'project_id', name='uq_plans_slot'),
    schema='finance'
    )
    op.create_index(op.f('ix_plans_workspace_id'), 'plans', ['workspace_id'], unique=False, schema='finance')
    op.create_index('ix_plans_workspace_id_month', 'plans', ['workspace_id', 'month'], unique=False, schema='finance')
    op.create_table('import_rows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('parsed', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('problems', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("state IN ('imported', 'skipped', 'failed', 'duplicate')", name=op.f('ck_import_rows_import_row_state')),
    sa.ForeignKeyConstraint(['batch_id'], ['finance.import_batches.id'], name=op.f('fk_import_rows_batch_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operation_id'], ['finance.operations.id'], name=op.f('fk_import_rows_operation_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_rows')),
    schema='finance'
    )
    op.create_index(op.f('ix_import_rows_batch_id'), 'import_rows', ['batch_id'], unique=False, schema='finance')
    op.create_index('ix_import_rows_batch_id_line', 'import_rows', ['batch_id', 'line'], unique=False, schema='finance')
    op.create_table('operation_projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_operation_projects_operation_project_amount_sign')),
    sa.ForeignKeyConstraint(['operation_id'], ['finance.operations.id'], name=op.f('fk_operation_projects_operation_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['finance.projects.id'], name=op.f('fk_operation_projects_project_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_projects')),
    sa.UniqueConstraint('operation_id', 'project_id', name='uq_operation_projects'),
    schema='finance'
    )
    op.create_index(op.f('ix_operation_projects_operation_id'), 'operation_projects', ['operation_id'], unique=False, schema='finance')
    op.create_index(op.f('ix_operation_projects_project_id'), 'operation_projects', ['project_id'], unique=False, schema='finance')
    op.create_table('operation_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['finance.operations.id'], name=op.f('fk_operation_tags_operation_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['finance.tags.id'], name=op.f('fk_operation_tags_tag_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_tags')),
    sa.UniqueConstraint('operation_id', 'tag_id', name='uq_operation_tags'),
    schema='finance'
    )
    op.create_index(op.f('ix_operation_tags_operation_id'), 'operation_tags', ['operation_id'], unique=False, schema='finance')
    op.create_index(op.f('ix_operation_tags_tag_id'), 'operation_tags', ['tag_id'], unique=False, schema='finance')
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_tags_tag_id'), table_name='operation_tags', schema='finance')
    op.drop_index(op.f('ix_operation_tags_operation_id'), table_name='operation_tags', schema='finance')
    op.drop_table('operation_tags', schema='finance')
    op.drop_index(op.f('ix_operation_projects_project_id'), table_name='operation_projects', schema='finance')
    op.drop_index(op.f('ix_operation_projects_operation_id'), table_name='operation_projects', schema='finance')
    op.drop_table('operation_projects', schema='finance')
    op.drop_index('ix_import_rows_batch_id_line', table_name='import_rows', schema='finance')
    op.drop_index(op.f('ix_import_rows_batch_id'), table_name='import_rows', schema='finance')
    op.drop_table('import_rows', schema='finance')
    op.drop_index('ix_plans_workspace_id_month', table_name='plans', schema='finance')
    op.drop_index(op.f('ix_plans_workspace_id'), table_name='plans', schema='finance')
    op.drop_table('plans', schema='finance')
    op.drop_index('ix_operations_workspace_id_status', table_name='operations', schema='finance')
    op.drop_index('ix_operations_workspace_id_paid_at', table_name='operations', schema='finance')
    op.drop_index('ix_operations_workspace_id_accrued_at', table_name='operations', schema='finance')
    op.drop_index(op.f('ix_operations_workspace_id'), table_name='operations', schema='finance')
    op.drop_table('operations', schema='finance')
    op.drop_index(op.f('ix_tags_workspace_id'), table_name='tags', schema='finance')
    op.drop_table('tags', schema='finance')
    op.drop_index('ix_projects_workspace_id_position', table_name='projects', schema='finance')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects', schema='finance')
    op.drop_table('projects', schema='finance')
    op.drop_index(op.f('ix_import_batches_workspace_id'), table_name='import_batches', schema='finance')
    op.drop_table('import_batches', schema='finance')
    op.drop_index('ix_counterparties_workspace_id_role', table_name='counterparties', schema='finance')
    op.drop_index(op.f('ix_counterparties_workspace_id'), table_name='counterparties', schema='finance')
    op.drop_table('counterparties', schema='finance')
    op.drop_index('ix_categories_workspace_id_side', table_name='categories', schema='finance')
    op.drop_index(op.f('ix_categories_workspace_id'), table_name='categories', schema='finance')
    op.drop_table('categories', schema='finance')
    op.drop_index('ix_accounts_workspace_id_position', table_name='accounts', schema='finance')
    op.drop_index(op.f('ix_accounts_workspace_id'), table_name='accounts', schema='finance')
    op.drop_table('accounts', schema='finance')
    op.drop_table('workspaces', schema='finance')
    # Схема пустеет вместе с последней таблицей — убираем и её: модуль обязан
    # сниматься начисто.
    op.execute(f'DROP SCHEMA IF EXISTS "{SCHEMA}"')
    # ### end Alembic commands ###
