"""finance: свои учётки и компании

Раздел «Финансы» перестаёт зависеть от учёток BBC Dashboard. Здесь появляются
его собственные `users`, `memberships` и `sessions`, а `workspaces` из ревизии
0012 становится компанией: у неё есть участники и владелец.

Почему членство отдельной таблицей, а не колонкой у пользователя
────────────────────────────────────────────────────────────────
Один человек ведёт несколько компаний — бухгалтер на подряде десяток. Колонка
`company_id` у пользователя заставила бы заводить ему вторую учётку с тем же
паролем, и смена пароля разъезжалась бы между ними. Роль тоже живёт на
членстве: один и тот же человек бывает владельцем своей компании и приглашённым
бухгалтером в чужой.

Про сессии
──────────
В cookie уходит случайный токен, здесь хранится его SHA-256: дамп базы не
должен давать работающих сессий. Компания, выбранная в сессии, — колонка
`workspace_id`: переключатель компаний меняет контекст, а не заводит вторую
сессию.

Revision ID: 0013
Revises: 0012
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0013'
down_revision: Union[str, None] = '0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SCHEMA = "finance"


def upgrade() -> None:
    bind = op.get_bind()
    # У SQLite схем нет — там таблицы собирает create_all из тех же моделей.
    if bind.dialect.name == "sqlite":
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('email_normalized', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email_normalized', name='uq_users_email_normalized'),
    schema='finance'
    )
    op.create_table('memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Text(), server_default=sa.text("'accountant'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("role IN ('owner', 'admin', 'accountant', 'viewer')", name=op.f('ck_memberships_membership_role')),
    sa.ForeignKeyConstraint(['invited_by'], ['finance.users.id'], name=op.f('fk_memberships_invited_by')),
    sa.ForeignKeyConstraint(['user_id'], ['finance.users.id'], name=op.f('fk_memberships_user_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['finance.workspaces.id'], name=op.f('fk_memberships_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_memberships_workspace_user'),
    schema='finance'
    )
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False, schema='finance')
    op.create_index(op.f('ix_memberships_workspace_id'), 'memberships', ['workspace_id'], unique=False, schema='finance')
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['finance.users.id'], name=op.f('fk_sessions_user_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['finance.workspaces.id'], name=op.f('fk_sessions_workspace_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name='uq_sessions_token_hash'),
    schema='finance'
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False, schema='finance')
    op.create_index('ix_sessions_user_id_expires_at', 'sessions', ['user_id', 'expires_at'], unique=False, schema='finance')
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_user_id_expires_at', table_name='sessions', schema='finance')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions', schema='finance')
    op.drop_table('sessions', schema='finance')
    op.drop_index(op.f('ix_memberships_workspace_id'), table_name='memberships', schema='finance')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships', schema='finance')
    op.drop_table('memberships', schema='finance')
    op.drop_table('users', schema='finance')
    # ### end Alembic commands ###
