"""finance: автоправила разметки

«В комментарии есть Magnum — это статья „Продукты“». Одна выписка Kaspi Gold за
год даёт две тысячи строк, и без правил отчёт покажет один столбец «Без
категории» на два миллиона тенге. Размечать руками столько никто не будет.

Правило — условия (`conditions`) и действия (`actions`) в jsonb. Форма условий
меняется чаще, чем что-либо ещё в модуле: сегодня «содержит», завтра «не
содержит» и «по регулярному выражению». Колонками это означало бы миграцию на
каждое новое сравнение.

`position` — порядок применения: первое сработавшее правило ставит значение,
следующие не перетирают. Иначе результат зависел бы от порядка строк в таблице,
а не от порядка правил.

`applied_count` — сколько операций правило разметило. Нужен, чтобы было видно
правило, которое не совпадает никогда: без счётчика оно выглядит как рабочее.

Revision ID: 0014
Revises: 0013
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0014'
down_revision: Union[str, None] = '0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('match', sa.Text(), server_default=sa.text("'all'"), nullable=False),
    sa.Column('conditions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('actions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('applied_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("match IN ('all', 'any')", name=op.f('ck_rules_rule_match')),
    sa.ForeignKeyConstraint(['workspace_id'], ['finance.workspaces.id'], name=op.f('fk_rules_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rules')),
    schema='finance'
    )
    op.create_index(op.f('ix_rules_workspace_id'), 'rules', ['workspace_id'], unique=False, schema='finance')
    op.create_index('ix_rules_workspace_id_position', 'rules', ['workspace_id', 'position'], unique=False, schema='finance')
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rules_workspace_id_position', table_name='rules', schema='finance')
    op.drop_index(op.f('ix_rules_workspace_id'), table_name='rules', schema='finance')
    op.drop_table('rules', schema='finance')
    # ### end Alembic commands ###
