"""finance: полный учёт — дробление, счета-фактуры, повторения, история, интеграции

Пять вещей, которых разделу не хватало против Finmap, и все пять — про данные,
а не про экраны:

* `operation_categories` — дробление платежа по статьям. Один платёж редко про
  одно, и без дробления он целиком падает в одну статью: отчёт врёт на всю
  разницу и об этом не сообщает.
* `invoices` / `invoice_lines` — счёт-фактура. Второй и главный источник долга,
  кроме ручного ожидания: выставили счёт — дебиторка появилась в тот момент,
  когда выставили. НДС хранится отдельно от суммы без налога, потому что в
  прибыль идёт одно, а в дебиторку другое.
* `recurrences` — аренда и зарплата раз в месяц руками это работа за
  программу. Правило порождает настоящие ожидания на горизонт вперёд, а не
  рисует их на экране.
* `action_log` — история с состоянием «до» и «после». Отмена возвращает ровно
  то, что было, а не «обратную операцию на глазок».
* `integrations` — подключения банков: выписка файлом, книга Google по
  расписанию и приём операций по нашему адресу с токеном. Токен хранится
  хешем: утечка базы не должна давать право писать в учёт.

Плюс `categories.nature`: без природы статьи не считаются ни валовая прибыль,
ни EBITDA — «Закуп товара» и «Аренда» оба расходы, но первый себестоимость, а
проценты и амортизация в EBITDA не входят вовсе.

Revision ID: 0015
Revises: 0014
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0015'
down_revision: Union[str, None] = '0014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('entity', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['finance.workspaces.id'], name=op.f('fk_action_log_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_log')),
    schema='finance'
    )
    op.create_index('ix_action_log_workspace_at', 'action_log', ['workspace_id', 'at'], unique=False, schema='finance')
    op.create_index(op.f('ix_action_log_workspace_id'), 'action_log', ['workspace_id'], unique=False, schema='finance')
    op.create_table('integrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), server_default=sa.text("'statement'"), nullable=False),
    sa.Column('state', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('token_hash', sa.Text(), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('api', 'statement', 'sheets')", name=op.f('ck_integrations_integration_kind')),
    sa.CheckConstraint("state IN ('draft', 'active', 'off')", name=op.f('ck_integrations_integration_state')),
    sa.ForeignKeyConstraint(['account_id'], ['finance.accounts.id'], name=op.f('fk_integrations_account_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['finance.workspaces.id'], name=op.f('fk_integrations_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations')),
    sa.UniqueConstraint('token_hash', name='uq_integrations_token'),
    schema='finance'
    )
    op.create_index(op.f('ix_integrations_workspace_id'), 'integrations', ['workspace_id'], unique=False, schema='finance')
    op.create_table('recurrences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('period', sa.Text(), server_default=sa.text("'month'"), nullable=False),
    sa.Column('day', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('start_at', sa.Date(), nullable=False),
    sa.Column('until', sa.Date(), nullable=True),
    sa.Column('next_at', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.Text(), server_default=sa.text("'KZT'"), nullable=False),
    sa.Column('account_from_id', sa.Uuid(), nullable=True),
    sa.Column('account_to_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('counterparty_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('comment', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_by', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('income', 'expense', 'transfer')", name=op.f('ck_recurrences_recurrence_kind')),
    sa.CheckConstraint("period IN ('week', 'month', 'quarter', 'year')", name=op.f('ck_recurrences_recurrence_period')),
    sa.ForeignKeyConstraint(['account_from_id'], ['finance.accounts.id'], name=op.f('fk_recurrences_account_from_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['account_to_id'], ['finance.accounts.id'], name=op.f('fk_recurrences_account_to_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['finance.categories.id'], name=op.f('fk_recurrences_category_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['finance.counterparties.id'], name=op.f('fk_recurrences_counterparty_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['finance.projects.id'], name=op.f('fk_recurrences_project_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['finance.workspaces.id'], name=op.f('fk_recurrences_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurrences')),
    schema='finance'
    )
    op.create_index(op.f('ix_recurrences_workspace_id'), 'recurrences', ['workspace_id'], unique=False, schema='finance')
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('number', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('issued_at', sa.Date(), nullable=False),
    sa.Column('due_at', sa.Date(), nullable=False),
    sa.Column('counterparty_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('currency', sa.Text(), server_default=sa.text("'KZT'"), nullable=False),
    sa.Column('amount_net', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=18, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('amount_gross', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('comment', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('out', 'in')", name=op.f('ck_invoices_invoice_kind')),
    sa.CheckConstraint("status IN ('draft', 'sent', 'paid', 'void')", name=op.f('ck_invoices_invoice_status')),
    sa.CheckConstraint('amount_net >= 0 AND vat_amount >= 0', name=op.f('ck_invoices_invoice_amount_sign')),
    sa.ForeignKeyConstraint(['category_id'], ['finance.categories.id'], name=op.f('fk_invoices_category_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['finance.counterparties.id'], name=op.f('fk_invoices_counterparty_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operation_id'], ['finance.operations.id'], name=op.f('fk_invoices_operation_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['finance.projects.id'], name=op.f('fk_invoices_project_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['finance.workspaces.id'], name=op.f('fk_invoices_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    schema='finance'
    )
    op.create_index('ix_invoices_workspace_due', 'invoices', ['workspace_id', 'due_at'], unique=False, schema='finance')
    op.create_index(op.f('ix_invoices_workspace_id'), 'invoices', ['workspace_id'], unique=False, schema='finance')
    op.create_table('operation_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('comment', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_operation_categories_operation_category_amount_sign')),
    sa.ForeignKeyConstraint(['category_id'], ['finance.categories.id'], name=op.f('fk_operation_categories_category_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operation_id'], ['finance.operations.id'], name=op.f('fk_operation_categories_operation_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_categories')),
    sa.UniqueConstraint('operation_id', 'category_id', name='uq_operation_categories'),
    schema='finance'
    )
    op.create_index(op.f('ix_operation_categories_category_id'), 'operation_categories', ['category_id'], unique=False, schema='finance')
    op.create_index(op.f('ix_operation_categories_operation_id'), 'operation_categories', ['operation_id'], unique=False, schema='finance')
    op.create_table('invoice_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), server_default=sa.text('1'), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['finance.invoices.id'], name=op.f('fk_invoice_lines_invoice_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_lines')),
    schema='finance'
    )
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False, schema='finance')
    op.add_column('categories', sa.Column('nature', sa.Text(), server_default=sa.text("'operating'"), nullable=False), schema='finance')
    op.create_check_constraint(
        'ck_categories_category_nature',
        'categories',
        "nature IN ('revenue', 'cogs', 'operating', 'financial', 'depreciation', 'tax', 'other', 'capital')",
        schema='finance',
    )
    # Уже заведённым компаниям природа начальных статей проставляется здесь,
    # иначе у них «Получение кредита» стало бы выручкой, а «Погашение кредита»
    # — операционным расходом. Сначала по системному ключу — он не меняется
    # при переименовании; потом по названию для двух статей без ключа, и только
    # тем, чья природа ещё умолчательная, чтобы не перетереть выбор человека.
    op.execute(
        "UPDATE finance.categories SET nature = 'capital' "
        "WHERE system_key IN ('loan_in', 'loan_return', 'loan_out', 'dividend')"
    )
    op.execute("UPDATE finance.categories SET nature = 'tax' WHERE system_key = 'tax'")
    op.execute(
        "UPDATE finance.categories SET nature = 'revenue' "
        "WHERE side = 'income' AND name = 'Выручка' AND nature = 'operating'"
    )
    op.execute(
        "UPDATE finance.categories SET nature = 'other' "
        "WHERE side = 'income' AND name = 'Прочий доход' AND nature = 'operating'"
    )
    op.execute(
        "UPDATE finance.categories SET nature = 'cogs' "
        "WHERE side = 'expense' AND name = 'Закуп товара' AND nature = 'operating'"
    )
    # Источников операции стало больше: счёт, повторение, интеграция. Список
    # закрытый, поэтому старое ограничение снимается и ставится новое — иначе
    # ожидание по счёту не запишется вовсе.
    op.drop_constraint('ck_operations_operation_source', 'operations', schema='finance')
    op.create_check_constraint(
        'ck_operations_operation_source',
        'operations',
        "source IN ('app', 'grid', 'import', 'api', 'invoice', 'recurrence', 'integration')",
        schema='finance',
    )
    op.add_column('operations', sa.Column('recurrence_id', sa.Uuid(), nullable=True), schema='finance')
    op.add_column('operations', sa.Column('integration_id', sa.Uuid(), nullable=True), schema='finance')
    op.create_foreign_key(op.f('fk_operations_integration_id'), 'operations', 'integrations', ['integration_id'], ['id'], source_schema='finance', referent_schema='finance', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_operations_recurrence_id'), 'operations', 'recurrences', ['recurrence_id'], ['id'], source_schema='finance', referent_schema='finance', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_operations_recurrence_id'), 'operations', schema='finance', type_='foreignkey')
    op.drop_constraint(op.f('fk_operations_integration_id'), 'operations', schema='finance', type_='foreignkey')
    op.drop_column('operations', 'integration_id', schema='finance')
    op.drop_column('operations', 'recurrence_id', schema='finance')
    op.drop_constraint('ck_operations_operation_source', 'operations', schema='finance')
    op.create_check_constraint(
        'ck_operations_operation_source',
        'operations',
        "source IN ('app', 'grid', 'import', 'api')",
        schema='finance',
    )
    # `IF EXISTS`, потому что откат делают на базе, которая могла и не получить
    # это ограничение: у наката была версия без него.
    op.execute("ALTER TABLE finance.categories DROP CONSTRAINT IF EXISTS ck_categories_category_nature")
    op.drop_column('categories', 'nature', schema='finance')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines', schema='finance')
    op.drop_table('invoice_lines', schema='finance')
    op.drop_index(op.f('ix_operation_categories_operation_id'), table_name='operation_categories', schema='finance')
    op.drop_index(op.f('ix_operation_categories_category_id'), table_name='operation_categories', schema='finance')
    op.drop_table('operation_categories', schema='finance')
    op.drop_index(op.f('ix_invoices_workspace_id'), table_name='invoices', schema='finance')
    op.drop_index('ix_invoices_workspace_due', table_name='invoices', schema='finance')
    op.drop_table('invoices', schema='finance')
    op.drop_index(op.f('ix_recurrences_workspace_id'), table_name='recurrences', schema='finance')
    op.drop_table('recurrences', schema='finance')
    op.drop_index(op.f('ix_integrations_workspace_id'), table_name='integrations', schema='finance')
    op.drop_table('integrations', schema='finance')
    op.drop_index(op.f('ix_action_log_workspace_id'), table_name='action_log', schema='finance')
    op.drop_index('ix_action_log_workspace_at', table_name='action_log', schema='finance')
    op.drop_table('action_log', schema='finance')
    # ### end Alembic commands ###
